# We have a conf and classes directory, but we have classes that should
# override those in oe-core, so prepend to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "lts-mixins"
BBFILE_PATTERN_lts-mixins := "^${LAYERDIR}/"
BBFILE_PRIORITY_lts-mixins = "9"

LAYERSERIES_COMPAT_lts-mixins = "scarthgap"

LAYERDEPENDS_lts-mixins = "core"

GOVERSION = "1.24%"
